name: Build and Archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.7.0

      - name: Install dependencies
        run: npm install

      - name: Add Banane SQLite database file
        run: mkdir -p bin && echo > bin/bananesdb.db

      - name: Build app
        run: npm run build

      - name: Remove src, .git and .gthub folder
        run: rm -rf src .github .git

      - name: Add .env file
        run: |
          echo "NODE_ENV=${{secrets.NODE_ENV}}" > .env
          echo "PORT=${{secrets.PORT}}" >> .env
          echo "SQLITE_DB_PATH=${{secrets.SQLITE_DB_PATH}}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}" >> .env

      - name: Uninstall DevDependencies
        run: npm prune --production

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: .
