name: Build and Archive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.7.0

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Archive project
        run: |
          zip -r project.zip .
          find . -type f -not -path "./src/*" -not -name "project.zip" -delete

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: project.zip
